name: Docker Build
on:
  workflow_dispatch:
    inputs:
      target:
        description: "Docker Image Tag"
        type: string
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.6"
  
      - name: goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --snapshot --config .goreleaser-nightly.yml

      - name: images
        shell: bash
        run: docker images
    
      - name: docker_login
        shell: bash
        run: docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASS }}"
  
      - name: docker_push
        shell: bash
        run: |
          NDATE=$(date +%Y%m%d)
      
          docker tag synadia/nats-server:nightly-${NDATE} synadia/nats-server:${{ inputs.label }}-${NDATE}
          docker tag synadia/nats-server:nightly-${NDATE} synadia/nats-server:${{ inputs.label }}
      
          docker push synadia/nats-server:${{ inputs.label }}-${NDATE}
          docker push synadia/nats-server:${{ inputs.label }}
